// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type LessonProgress struct {
	ID           int64
	UserID       int64
	Language     string
	LessonID     string
	Status       string
	BestScore    sql.NullInt64
	Attempts     sql.NullInt64
	LastAccessed sql.NullTime
	CompletedAt  sql.NullTime
}

type QuizAttempt struct {
	ID             int64
	UserID         int64
	Language       string
	LessonID       string
	Score          int64
	TotalQuestions int64
	CorrectAnswers int64
	AttemptedAt    sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	DisplayName  string
	CreatedAt    sql.NullTime
}

type VocabProgress struct {
	ID             int64
	UserID         int64
	Language       string
	WordID         string
	TimesCorrect   sql.NullInt64
	TimesIncorrect sql.NullInt64
	MasteryLevel   sql.NullInt64
	LastReviewed   sql.NullTime
}
